import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}, bg-blue-50`}>
        {children}
        <footer className="bg-blue-900 text-center py-2">
          <div className="container px-4 mx-auto">
            <span className="text-sm text-blue-300">© Khaitan & Co 2023</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
